export enum AuditAction {
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",

  CREATE = "CREATE",
  UPDATE = "UPDATE",
  DELETE = "DELETE",

  GENERATE_LICENSE = "GENERATE_LICENSE",
  ACTIVATE_LICENSE = "ACTIVATE_LICENSE",
  VALIDATE_LICENSE = "VALIDATE_LICENSE",
  RENEW_LICENSE = "RENEW_LICENSE",
  REVOKE_LICENSE = "REVOKE_LICENSE",

  CREATE_PRODUCT = "CREATE_PRODUCT",
  UPDATE_PRODUCT = "UPDATE_PRODUCT",
  DELETE_PRODUCT = "DELETE_PRODUCT",

  CREATE_CUSTOMER = "CREATE_CUSTOMER",
  UPDATE_CUSTOMER = "UPDATE_CUSTOMER",
  DELETE_CUSTOMER = "DELETE_CUSTOMER",
}