export enum EventType {
  USER_LOGIN = "USER_LOGIN",
  USER_LOGOUT = "USER_LOGOUT",

  PRODUCT_CREATED = "PRODUCT_CREATED",
  PRODUCT_UPDATED = "PRODUCT_UPDATED",
  PRODUCT_DELETED = "PRODUCT_DELETED",

  CUSTOMER_CREATED = "CUSTOMER_CREATED",
  CUSTOMER_UPDATED = "CUSTOMER_UPDATED",
  CUSTOMER_DELETED = "CUSTOMER_DELETED",

  LICENSE_GENERATED = "LICENSE_GENERATED",
  LICENSE_ACTIVATED = "LICENSE_ACTIVATED",
  LICENSE_VALIDATED = "LICENSE_VALIDATED",
  LICENSE_RENEWED = "LICENSE_RENEWED",
  LICENSE_REVOKED = "LICENSE_REVOKED",
}